// 출처 : https://trends.google.co.kr/trending?geo=KR&hl=ko
export const topSearch = [
   '배드민턴 협회',
   '네이버 로그인',
   '고영욱',
   '루아나 알론소',
   '입추',
   '동아리 깐부',
   '데이비드 용',
   '신지은',
   '방글라데시',
   '더 인플루언서',
   '김홍걸',
   'luana alonso',
   '전도연 유재석',
   '미용실 먹튀 연예인 부부',
   '진성준',
   'ev6 화재',
   '서채현',
   '송승준',
   '이건주',
   '허영만',
   '토익',
   '부산날씨',
   '이스타항공',
   '앙토니 아미라티',
   '네이버 쇼핑',
   '마후치크',
   '경북대학교',
   '목포대학교',
   '한국도로공사',
   '아이빔테크놀로지',
   '이은혜 탁구',
   '이승찬',
   '다우지수',
   '아모레퍼시픽',
   '팔란티어 주가',
   '래미안 레벤투스',
   '군산대학교',
   'ev6',
   '매수 사이드카',
   '윤수현',
   '행정안전부',
   '만나플러스',
   '라이엇',
   '모로코',
   '계명대학교',
   '인터파크',
   '아티스틱 스위밍 남자',
   '리그오브레전드',
   'pmi',
   '올림픽 순위',
   'nasdaq index',
   '배도환',
   '키움증권',
   '대한민국 2024년 올림픽',
   '번개',
   '김태호',
   '비치발리볼',
   '김승현',
   '모로코 스페인',
   '우상혁',
   '토스증권',
   '백석대',
   '광복절',
   '솔랑케',
   'bangladesh',
   '칸예',
   '알테오젠',
   '하이닉스 주가',
   '나스닥 주가',
   '올림픽 배구',
   '알라딘 뮤지컬',
   '한국공학대학교',
   'ism 서비스업 지수',
   '시간',
   '경북대',
   '2ne1 콘서트',
   'nikkei 225',
   '나무증권',
   '이도현',
   '시계',
   '올림픽 중계',
   '엔화환율',
   '조영재 사격',
   '최진희',
   '이순재',
   '블루오션 거래소',
   'sbs',
   'nvda',
   'riot',
   'kb증권',
   '증권',
   'ism',
   '파리올림픽 중계',
   '몰도바',
   '라트비아',
   '파리올림픽 태권도',
   '수능',
   '박세완',
   'simone biles',
   'league of legends',
   '빅토리',
   'vix index',
   '금메달 연금',
   'a',
   '현영',
   '구교환',
   '박주호',
   '김성주',
   'nvidia 주가',
   '임지연',
   '연준',
   '웨이브',
   'kbs 올림픽',
   '줄리엔강',
   '풋옵션',
   '홍텐',
   '올림픽 기간',
   '파리올림픽 메달',
   '세븐',
   '테슬라주가',
   '남주혁',
   '오징어게임2',
   '세징야',
   '넷마블',
];

export const youtubeData = {
   kind: 'youtube#searchListResponse',
   etag: 'sJJbuDagJftEr5SqihlEa9zEOR0',
   nextPageToken: 'CBQQAA',
   regionCode: 'KR',
   pageInfo: {
      totalResults: 176518,
      resultsPerPage: 20,
   },
   items: [
      {
         kind: 'youtube#searchResult',
         etag: '5UfDVoHMYANesriyMuHEkEUkFoA',
         id: {
            kind: 'youtube#video',
            videoId: 'EgcclXZFKXk',
         },
         snippet: {
            publishedAt: '2024-08-04T07:22:50Z',
            channelId: 'UC84OTRAO0FMDgMY1u9pbOBg',
            title: '엔비디아(nvda) 정말 하락장 시작이어서 다던져야 되나?',
            description: '안녕하세요 올랜도 킴입니다 경기침체의 실질적인 의미를 찿아보고 왜 지금이 조정일 가능성이 많은지에 관해서 알아보자#엔비디아# ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/EgcclXZFKXk/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/EgcclXZFKXk/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/EgcclXZFKXk/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '올랜도 킴 미국주식',
            liveBroadcastContent: 'none',
            publishTime: '2024-08-04T07:22:50Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'o2O5aNsxvQnYUkBSYOSIOqP_YrA',
         id: {
            kind: 'youtube#video',
            videoId: 'Ig5OM1Q_1oQ',
         },
         snippet: {
            publishedAt: '2024-08-02T05:42:32Z',
            channelId: 'UC84OTRAO0FMDgMY1u9pbOBg',
            title: '엔비디아(nvda) 정말 경기침체로 주가가 하락했나?',
            description: '안녕하세요 올랜도 킴입니다 엔케리 자금 즉 엔 금리 인상으로 인한 주가하락의 원인을 찿아보고 펀더멘탈을 통해 매매시점을 알아 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/Ig5OM1Q_1oQ/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/Ig5OM1Q_1oQ/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/Ig5OM1Q_1oQ/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '올랜도 킴 미국주식',
            liveBroadcastContent: 'none',
            publishTime: '2024-08-02T05:42:32Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: '9xB2smkbrZBiZtu4MVyaFVmZpAA',
         id: {
            kind: 'youtube#video',
            videoId: 'PPmuVGXe36M',
         },
         snippet: {
            publishedAt: '2024-08-04T13:42:56Z',
            channelId: 'UCczff_dQVVb9sSEULFUJ-sw',
            title: '위기의 엔비디아?! 기회인가?  중간점검: 살까? 팔까? 적정주가, 목표주가, 기관흐름, 최근 동향, 내부자 거래, 시장 점유율, 공매도 흐름, 실적 전망 #nvidia $nvda',
            description: "저서:'다시 오는 기회, 미국 주식이 답이다'(미국 로스쿨 교수가 20년간 미국 주식시장을 관찰하며 깨달은 '10년 후' 시장): ...",
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/PPmuVGXe36M/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/PPmuVGXe36M/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/PPmuVGXe36M/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '반교수(ProfHalf)의 미국 투자 스토리 (미투리)',
            liveBroadcastContent: 'none',
            publishTime: '2024-08-04T13:42:56Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'teNriN3d8zsW0I4WFvZ4nlo5xW4',
         id: {
            kind: 'youtube#video',
            videoId: '9vg_StYW7U0',
         },
         snippet: {
            publishedAt: '2024-08-01T00:25:50Z',
            channelId: 'UCkinYTS9IHqOEwR1Sze2JTw',
            title: '엔비디아 주가 13% 가까이 폭등…&#39;AI 거품론&#39; 대두 / SBS / 친절한 경제',
            description: '〈앵커〉 목요일 친절한 경제 오늘(1일)은 경제부 노동규 기자 나와 있습니다. 노 기자, 많이 익숙한 회사네요. AI 반도체 선두주자인 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/9vg_StYW7U0/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/9vg_StYW7U0/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/9vg_StYW7U0/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: 'SBS 뉴스',
            liveBroadcastContent: 'none',
            publishTime: '2024-08-01T00:25:50Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'arDO2IafsGqgicxHToUj2x6BhEA',
         id: {
            kind: 'youtube#video',
            videoId: '90V6gybJvPU',
         },
         snippet: {
            publishedAt: '2024-07-26T15:02:18Z',
            channelId: 'UCdEtDJZiZCJyUSr1oNJ1jqw',
            title: '엔비디아 1년 안에 200불에 도달합니다',
            description: '멤버십 혜택 아인의 엘리엇파동 분석 강의 해외선물 시황 개별주 분석(국장, 미장) 멤버십 가입 링크 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/90V6gybJvPU/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/90V6gybJvPU/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/90V6gybJvPU/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '아인의 주식투자',
            liveBroadcastContent: 'none',
            publishTime: '2024-07-26T15:02:18Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: '8_dRey-kjkuSKfgD4shLEN9ziHk',
         id: {
            kind: 'youtube#video',
            videoId: '7OwHt0NXJto',
         },
         snippet: {
            publishedAt: '2024-06-19T22:57:09Z',
            channelId: 'UCznImSIaxZR7fdLCICLdgaQ',
            title: '시총 1위가 된 엔비디아, 주식 매도시기는?',
            description: '주식 #투자 #나스닥#미국주식#코스피 2024년 하반기 주식뭐사야 할까? 7/6(서울) : https://bit.ly/3wTuQ6Z 7/7(부산) ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/7OwHt0NXJto/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/7OwHt0NXJto/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/7OwHt0NXJto/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '전인구경제연구소',
            liveBroadcastContent: 'none',
            publishTime: '2024-06-19T22:57:09Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'UXSSyRiVoWim7alYjrqjxoeNndg',
         id: {
            kind: 'youtube#video',
            videoId: 'BhclZlC_Pao',
         },
         snippet: {
            publishedAt: '2024-08-02T02:49:45Z',
            channelId: 'UCbMjg2EvXs_RUGW-KrdM3pw',
            title: '&#39;엔비디아 독점&#39; 균열?…심상치 않은 주가 변동성',
            description: "[앵커] 이번 주 엔비디아 주가가 크게 출렁였습니다. 인공지능 관련주들의 미래가 불확실하다, '엔비디아 천하'는 이제 끝났다, 온갖 ...",
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/BhclZlC_Pao/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/BhclZlC_Pao/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/BhclZlC_Pao/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: 'SBS Biz 뉴스',
            liveBroadcastContent: 'none',
            publishTime: '2024-08-02T02:49:45Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: '7_5RqoxBHXqzX6_JIrkMm2jEIpg',
         id: {
            kind: 'youtube#video',
            videoId: 'KrdvOGdci0Q',
         },
         snippet: {
            publishedAt: '2024-08-01T22:50:00Z',
            channelId: 'UCbRPwVrz9VDdwnCC4h8Vzyg',
            title: '나스닥, 엔비디아, 테슬라 동반 폭락한 진짜 이유. 평소와는 다릅니다!',
            description: '나스닥, 엔비디아, 테슬라 동반 폭락한 진짜 이유. 평소와는 다릅니다! 캐쉬 비중은 30%정도 가지고 있으면 조정장에 대응 가능 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/KrdvOGdci0Q/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/KrdvOGdci0Q/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/KrdvOGdci0Q/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '미국주식하는인갠',
            liveBroadcastContent: 'none',
            publishTime: '2024-08-01T22:50:00Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: '7UZM3Rkrdsh33kBJWxW-xNFCJoY',
         id: {
            kind: 'youtube#video',
            videoId: 'DhxdyizqWfY',
         },
         snippet: {
            publishedAt: '2024-08-04T03:00:07Z',
            channelId: 'UCpSl2_CA4MWkLJ-16V65TTA',
            title: '엔비디아 주식 전망!!',
            description: '안녕하세요? 올바른 투자를 지향하는 올투입니다. 여러분의 올바른 투자를 기원합니다. 올투!! 제 블로그에 다양한 투자 관련 자료를 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/DhxdyizqWfY/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/DhxdyizqWfY/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/DhxdyizqWfY/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '올바른 투자를 지향하는 올투의 주식 채널',
            liveBroadcastContent: 'none',
            publishTime: '2024-08-04T03:00:07Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'YJx_k65J_dX_bddMpwJPYxbKCTY',
         id: {
            kind: 'youtube#video',
            videoId: 'Cre9DbsMo9c',
         },
         snippet: {
            publishedAt: '2024-07-17T08:30:02Z',
            channelId: 'UCMupe3fvv1-Hi3SRxZzSsTw',
            title: '긴급 속보! 엔비디아 및 기술주 하락 신호? - ASML 3분기 전망 부진 소식',
            description: '미국주식 #나스닥 #주식시황 #경제뉴스 #연준.',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/Cre9DbsMo9c/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/Cre9DbsMo9c/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/Cre9DbsMo9c/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '미국 주식 채널 - 에디 Eddie',
            liveBroadcastContent: 'none',
            publishTime: '2024-07-17T08:30:02Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'R3Q-gD8nN0iXMVnBBjgmuVzJjmw',
         id: {
            kind: 'youtube#video',
            videoId: 'fnOwwEF0nNY',
         },
         snippet: {
            publishedAt: '2024-06-25T00:31:44Z',
            channelId: 'UChlgI3UHCOnwUGzWzbJ3H5w',
            title: '시총 288조 원 증발...엔비디아 주가 &#39;곤두박질&#39; [지금이뉴스] / YTN',
            description: '거침없는 상승세를 이어가던 AI 칩 선두 주자 엔비디아 주가가 3거래일째 연속해서 큰 폭으로 하락했습니다. 현지 시간 24일 뉴욕 증시 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/fnOwwEF0nNY/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/fnOwwEF0nNY/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/fnOwwEF0nNY/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: ' YTN',
            liveBroadcastContent: 'none',
            publishTime: '2024-06-25T00:31:44Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'N2TffoQGQqMzvsB-gTIA0XCNzEA',
         id: {
            kind: 'youtube#video',
            videoId: 'CDHsNf5Dzvo',
         },
         snippet: {
            publishedAt: '2024-06-13T09:00:08Z',
            channelId: 'UCgjsiInAgdceEq2lpRNNYvw',
            title: '엔비디아 이제라도 살까 말까? 8년전 상승 예측한  전문가가 알려드립니다ㅣ장우석 부사장(2부)',
            description: '엔비디아 #엔비디아시총 #장우석부사장 #장비디아 #엔비디아주가 #서학개미 #배당주 #배당성장주 #슈드 #DGRW #배당ETF ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/CDHsNf5Dzvo/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/CDHsNf5Dzvo/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/CDHsNf5Dzvo/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '경제야놀자',
            liveBroadcastContent: 'none',
            publishTime: '2024-06-13T09:00:08Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'bWQfhqO6Czg-o9Pi9Mha7JF0iTM',
         id: {
            kind: 'youtube#video',
            videoId: 'mAacZa8nHIc',
         },
         snippet: {
            publishedAt: '2024-05-29T08:49:10Z',
            channelId: 'UC7cF2ZYvGm_zgrX-xCV88mA',
            title: '엔비디아 언제 팔까…월가 &quot;258% 더 오른다&quot;/한국경제TV뉴스',
            description: '연일 사상 최고가를 쓰고 있는 엔비디아 주가가 1100달러 선을 넘어섰습니다. 미국 월가에서는 엔비디아 주가가 앞으로 3배 이상 더 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/mAacZa8nHIc/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/mAacZa8nHIc/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/mAacZa8nHIc/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '한국경제TV뉴스',
            liveBroadcastContent: 'none',
            publishTime: '2024-05-29T08:49:10Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'OxZf-BpgsCnL_nFUunO6Bv7B6d8',
         id: {
            kind: 'youtube#video',
            videoId: 'BmIZ3A-65g4',
         },
         snippet: {
            publishedAt: '2024-07-12T03:12:13Z',
            channelId: 'UC84OTRAO0FMDgMY1u9pbOBg',
            title: '엔비디아(nvda) 팔고 떠나야하나?',
            description: '안녕하세요 올랜도 킴입니다 주가하락의 원인과 앞으로의 전망을 알아보고 챠트비교를 통해서 어떻게 대응해야 할지를 알아보자, ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/BmIZ3A-65g4/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/BmIZ3A-65g4/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/BmIZ3A-65g4/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '올랜도 킴 미국주식',
            liveBroadcastContent: 'none',
            publishTime: '2024-07-12T03:12:13Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'VVhd8hhh57JJN6RXkYuDXbiJoEg',
         id: {
            kind: 'youtube#video',
            videoId: 'o6w07gqRY8A',
         },
         snippet: {
            publishedAt: '2024-06-23T22:43:23Z',
            channelId: 'UC84OTRAO0FMDgMY1u9pbOBg',
            title: '엔비디아(nvda) 6/26 이전이 왜 중요한지 알아보자?',
            description: '안녕하세요 올랜도 킴입니다 동종업체의 실적을 보면서 엔비디아의 주가와 비교하면서 매매타이밍을 잡아보자. #엔비디아#반도체 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/o6w07gqRY8A/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/o6w07gqRY8A/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/o6w07gqRY8A/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '올랜도 킴 미국주식',
            liveBroadcastContent: 'none',
            publishTime: '2024-06-23T22:43:23Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'ZiyK01-ADUz3tvSIR9dilderTh0',
         id: {
            kind: 'youtube#video',
            videoId: 'J0judIXBe8k',
         },
         snippet: {
            publishedAt: '2024-06-11T00:43:03Z',
            channelId: 'UChlgI3UHCOnwUGzWzbJ3H5w',
            title: '&quot;16만 원이면 산다&quot;...&#39;액면분할&#39; 엔비디아, 지금이 매수 시점? [Y녹취록] / YTN',
            description: '진행 : 이정섭 앵커, 조예진 앵커 □ 출연 : 허준영 교수 서강대학교 경제학부 * 아래 텍스트는 실제 방송 내용과 차이가 있을 수 있으니 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/J0judIXBe8k/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/J0judIXBe8k/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/J0judIXBe8k/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: ' YTN',
            liveBroadcastContent: 'none',
            publishTime: '2024-06-11T00:43:03Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'WTCQrMyTlNU5q22q-S46GR49ZJ0',
         id: {
            kind: 'youtube#video',
            videoId: 'mtHnRP_Mjk4',
         },
         snippet: {
            publishedAt: '2024-08-01T20:25:31Z',
            channelId: 'UCczff_dQVVb9sSEULFUJ-sw',
            title: '미국주식시황/오늘 왜 반도체 폭락했나? 테슬라 엔비디아는 왜 폭락했나? 인텔 아마존? 구글 애플 메타 마이크로소프트 팔란티어 아이온큐 ARM 콸컴 브로드컴 $tsla #tesla',
            description: "저서:'다시 오는 기회, 미국 주식이 답이다'(미국 로스쿨 교수가 20년간 미국 주식시장을 관찰하며 깨달은 '10년 후' 시장): ...",
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/mtHnRP_Mjk4/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/mtHnRP_Mjk4/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/mtHnRP_Mjk4/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '반교수(ProfHalf)의 미국 투자 스토리 (미투리)',
            liveBroadcastContent: 'none',
            publishTime: '2024-08-01T20:25:31Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: '39P4T9YTDv3FtT23R9wdqhOtLzg',
         id: {
            kind: 'youtube#video',
            videoId: '4KQhQOTC51Q',
         },
         snippet: {
            publishedAt: '2024-07-18T10:24:32Z',
            channelId: 'UCbMjg2EvXs_RUGW-KrdM3pw',
            title: '[이슈체크] 엔비디아 주가 6% 이상 &#39;급락&#39;…미국發 &#39;반도체 패닉&#39;',
            description: '[집중진단] 일단 던지고 본다! 트럼프발 폭탄...영향은? - 양준석 / 가톨릭대 경제학과 교수 - 염정 / 하이투자증권 신사업추진팀 차장장 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/4KQhQOTC51Q/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/4KQhQOTC51Q/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/4KQhQOTC51Q/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: 'SBS Biz 뉴스',
            liveBroadcastContent: 'none',
            publishTime: '2024-07-18T10:24:32Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'MtRbbjSUqUlRNKc9ZXrmCkuJj0g',
         id: {
            kind: 'youtube#video',
            videoId: 'saPaI9sq7RA',
         },
         snippet: {
            publishedAt: '2024-08-04T03:46:42Z',
            channelId: 'UCnwTpaRmErJXgJTrVixeSNA',
            title: '머스크의 자신감 넘치는 이유! 엔비디아 악재! 주가 추가폭락 하나? 워렌버핏 애플주식 절반 매도 이유! 경기침체를 대비하나? 애플의 미래가 없나? 테슬라 빌드업 되고있다!',
            description: '테슬라 #엔비디아 #비트코인 LA 정교수 미국주식 온라인강의 커리큘럼 확인하기: ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/saPaI9sq7RA/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/saPaI9sq7RA/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/saPaI9sq7RA/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: 'LA 정교수 TV',
            liveBroadcastContent: 'none',
            publishTime: '2024-08-04T03:46:42Z',
         },
      },
      {
         kind: 'youtube#searchResult',
         etag: 'VezGpTavfLd8c5fUG35W1j6pcUU',
         id: {
            kind: 'youtube#video',
            videoId: '9EQFoUoADs8',
         },
         snippet: {
            publishedAt: '2024-06-21T03:54:29Z',
            channelId: 'UC84OTRAO0FMDgMY1u9pbOBg',
            title: '엔비디아(nvda) 급락의 이유를 알아보고 반등이 어디서 부터 되는지 알아보자.',
            description: '안녕하세요 올랜도 킴입니다 주가상승의 원인이 어디서부터 기인하는지 알아보고 엔비디아가 아직 더욱상승할수 있는 이유를 알아 ...',
            thumbnails: {
               default: {
                  url: 'https://i.ytimg.com/vi/9EQFoUoADs8/default.jpg',
                  width: 120,
                  height: 90,
               },
               medium: {
                  url: 'https://i.ytimg.com/vi/9EQFoUoADs8/mqdefault.jpg',
                  width: 320,
                  height: 180,
               },
               high: {
                  url: 'https://i.ytimg.com/vi/9EQFoUoADs8/hqdefault.jpg',
                  width: 480,
                  height: 360,
               },
            },
            channelTitle: '올랜도 킴 미국주식',
            liveBroadcastContent: 'none',
            publishTime: '2024-06-21T03:54:29Z',
         },
      },
   ],
};
